version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=fashion_ecommerce
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - ./app:/app/app
      - ./raw_data:/app/raw_data
    depends_on:
      - db

  db:
    build:
      context: ./app/database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fashion_ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 